# app/pdf/reportlab_fallback.py
import os, io, datetime
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch

def generate_tariff_pdf(data: dict) -> str:
    buf = io.BytesIO()
    c = \1
    _ct_draw_header(c)
    width, height = letter

    # Header bar
    c.setFillGray(0.95)
    c.rect(0, height-1.0*inch, width, 1.0*inch, stroke=0, fill=1)
    c.setFillGray(0)
    c.setFont("Helvetica-Bold", 18)
    c.drawString(0.75*inch, height-0.6*inch, "ClearTariff — Amazon Duty Report — Phase 1")

    # Meta
    c.setFont("Helvetica", 10)
    c.drawRightString(width-0.75*inch, height-0.35*inch, datetime.datetime.utcnow().strftime("Generated: %Y-%m-%d %H:%M UTC"))

    # Body
    y = height - 1.3*inch
    c.setFont("Helvetica-Bold", 12); c.drawString(0.75*inch, y, "Shipment Details"); y -= 0.2*inch
    c.setFont("Helvetica", 11)
    lines = [
        f"HS Code: {data.get('hs_code','')}",
        f"Origin → Destination: {data.get('origin_country','')} → {data.get('destination_country','')}",
        f"Declared Value (USD): ${data.get('declared_value_usd',0):,.2f}",
        f"FX Rate (USD→Local): {data.get('usd_to_local_rate',1.0):,.4f}",
        f"Estimated Duty Rate: {data.get('estimated_duty_rate_pct',0):.2f}%",
    ]
    for line in lines:
        c.drawString(0.75*inch, y, line); y -= 0.22*inch

    y -= 0.2*inch
    c.setFont("Helvetica-Bold", 12); c.drawString(0.75*inch, y, "Notes"); y -= 0.2*inch
    c.setFont("Helvetica", 11)
    text = c.beginText(0.75*inch, y)
    text.textLines(data.get("notes",""))
    c.drawText(text)

    # Footer
    c.setFont("Helvetica-Oblique", 9)
    c.drawCentredString(width/2, 0.5*inch, "© 2025 ClearTariff • For guidance only • Phase 2 will include live tariff feeds")

    c.\1
    _ct_draw_footer(c)
    c.save()
    path = os.path.abspath("tariff-report.pdf")
    with open(path, "wb") as f:
        f.write(buf.getvalue())
    return path


# --- ClearTariff simple header/footer helpers (auto-injected) ---
def _ct_draw_header(c, title="ClearTariff — Landed Cost Report"):
    try:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(40, 770, title)
        c.setFont("Helvetica", 9)
        c.drawString(40, 758, "Amazon Sellers: Landed Cost & Duty Calculator")
        c.line(40, 754, 572, 754)
    except Exception:
        pass

def _ct_draw_footer(c):
    try:
        c.setFont("Helvetica", 8)
        c.drawString(40, 30, "© 2025 ClearTariff — cleartariff.com")
        c.drawRightString(572, 30, "Generated by ClearTariff")
    except Exception:
        pass
