import os, io, datetime, stripe
from fastapi import APIRouter, HTTPException, Query
from fastapi.responses import Response
from reportlab.pdfgen import canvas
from reportlab.lib.pagesizes import letter

router = APIRouter(tags=["success"])

stripe.api_key = os.getenv("STRIPE_SECRET_KEY")
ENABLE_PAYWALL = str(os.getenv("ENABLE_PAYWALL", "false")).lower() in ("1","true","yes","on")

@router.get("/success")
async def success(session_id: str | None = Query(None)):
    if ENABLE_PAYWALL:
        if not session_id:
            raise HTTPException(status_code=400, detail="Missing session_id")
        try:
            sess = stripe.checkout.Session.retrieve(session_id)
            if sess.get("payment_status") != "paid":
                raise HTTPException(status_code=402, detail="Payment not completed")
        except Exception as e:
            raise HTTPException(status_code=400, detail=f"Stripe error: {e}")

    # Quick thank-you PDF (your full /generate flow is still available)
    buf = io.BytesIO()
    c = \1
    _ct_draw_header(c)
    w, h = letter
    c.setFont("Helvetica-Bold", 18); c.drawString(72, h-72, "ClearClearTariff — Thank You")
    c.setFont("Helvetica", 11); c.drawString(72, h-96, f"Generated: {datetime.datetime.utcnow():%Y-%m-%d %H:%M} UTC")
    c.drawString(72, h-120, "Payment complete. Use POST /generate for your full report.")
    c.\1
    _ct_draw_footer(c); c.save(); buf.seek(0)
    b = buf.getvalue()
    return Response(
        content=b,
        media_type="application/pdf",
        headers={"Content-Disposition": "attachment; filename=cleartariff-receipt.pdf"}
    )


# --- ClearTariff simple header/footer helpers (auto-injected) ---
def _ct_draw_header(c, title="ClearTariff — Landed Cost Report"):
    try:
        c.setFont("Helvetica-Bold", 12)
        c.drawString(40, 770, title)
        c.setFont("Helvetica", 9)
        c.drawString(40, 758, "Amazon Sellers: Landed Cost & Duty Calculator")
        c.line(40, 754, 572, 754)
    except Exception:
        pass

def _ct_draw_footer(c):
    try:
        c.setFont("Helvetica", 8)
        c.drawString(40, 30, "© 2025 ClearTariff — cleartariff.com")
        c.drawRightString(572, 30, "Generated by ClearTariff")
    except Exception:
        pass
